### ISSUE TITLE
cannot install on windows11

### ISSUE THREAD

**Issue by IWannaToBeHappy** [rusty1s/pytorch_cluster#146]
I try to install using 'pip install torch-cluster -f https://data.pyg.org/whl/torch-1.12.1+cpu.html'
but wheel cannot run successfully: "Preparing metadata (setup.py) ... done
Building wheels for collected packages: torch-cluster
  Building wheel for torch-cluster (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
..."
python:3.7.4
torch: 1.12.1
wheel: 0.36.2

**Comment by IWannaToBeHappy** [comment]
this is full info:
`Preparing metadata (setup.py) ... done
Building wheels for collected packages: torch_cluster
  Building wheel for torch_cluster (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\fps.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\graclus.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\grid.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\knn.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\nearest.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\radius.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\rw.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\sampler.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\__init__.py -> build\lib.win-amd64-cpython-37\torch_cluster
      running egg_info
      writing torch_cluster.egg-info\PKG-INFO
      writing dependency_links to torch_cluster.egg-info\dependency_links.txt
      writing requirements to torch_cluster.egg-info\requires.txt
      writing top-level names to torch_cluster.egg-info\top_level.txt        
      reading manifest file 'torch_cluster.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-o4dhlcg5\torch-cluster_98f7091699c2480387c42d120af49244\setup.py", line 124, in <module>
          include_package_data=True,
        File "env\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "env\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "env\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "env\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "env\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "env\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "env\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "env\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "env\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "env\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "env\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "env\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "env\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "env\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "env\lib\site-packages\setuptools\command\build_py.py", line 63, in run
          self.build_package_data()
        File "env\lib\site-packages\setuptools\command\build_py.py", line 159, in build_package_data
          for target, srcfile in self._get_package_data_output_mapping():    
        File "env\lib\site-packages\setuptools\command\build_py.py", line 151, in _get_package_data_output_mapping
          for package, src_dir, build_dir, filenames in self.data_files:     
        File "env\lib\site-packages\setuptools\command\build_py.py", line 72, in __getattr__
          self.data_files = self._get_data_files()
        File "env\lib\site-packages\setuptools\command\build_py.py", line 84, in _get_data_files
          self.analyze_manifest()
        File "env\lib\site-packages\setuptools\command\build_py.py", line 181, in analyze_manifest
          self.run_command('egg_info')
        File "env\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "env\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "env\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "env\lib\site-packages\setuptools\command\egg_info.py", line 308, in run
          self.find_sources()
        File "env\lib\site-packages\setuptools\command\egg_info.py", line 316, in find_sources
          mm.run()
        File "env\lib\site-packages\setuptools\command\egg_info.py", line 560, in run
          self.add_defaults()
        File "env\lib\site-packages\setuptools\command\egg_info.py", line 604, in add_defaults
          self.read_manifest()
        File "env\lib\site-packages\setuptools\command\sdist.py", line 209, in read_manifest
          self.filelist.append(line)
        File "env\lib\site-packages\setuptools\command\egg_info.py", line 497, in append
          path = convert_path(item)
        File "env\lib\site-packages\setuptools\_distutils\util.py", line 137, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)        
      ValueError: path '/Users/rusty1s/github/pytorch_cluster/csrc/fps.cpp' cannot be absolute
      Error in atexit._run_exitfuncs:
      Traceback (most recent call last):
        File "env\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
          return stream.closed
      ValueError: underlying buffer has been detached
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torch_cluster
  Running setup.py clean for torch_cluster
Failed to build torch_cluster
Installing collected packages: torch_cluster
  Running setup.py install for torch_cluster ... error
  error: subprocess-exited-with-error

  × Running setup.py install for torch_cluster did not run successfully.     
  │ exit code: 1
  ╰─> [96 lines of output]
      running install
      env\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\fps.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\graclus.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\grid.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\knn.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\nearest.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\radius.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\rw.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\sampler.py -> build\lib.win-amd64-cpython-37\torch_cluster
      copying torch_cluster\__init__.py -> build\lib.win-amd64-cpython-37\torch_cluster
      running egg_info
      writing torch_cluster.egg-info\PKG-INFO
      writing dependency_links to torch_cluster.egg-info\dependency_links.txt
      writing requirements to torch_cluster.egg-info\requires.txt
      writing top-level names to torch_cluster.egg-info\top_level.txt        
      reading manifest file 'torch_cluster.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "somepath\torch-cluster_98f7091699c2480387c42d120af49244\setup.py", line 124, in <module>
          include_package_data=True,
        File "env\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "env\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "env\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "env\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "env\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "env\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "env\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "env\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "env\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "env\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "env\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "env\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "env\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "env\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "env\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "env\lib\site-packages\setuptools\command\build_py.py", line 63, in run
          self.build_package_data()
        File "env\lib\site-packages\setuptools\command\build_py.py", line 159, in build_package_data
          for target, srcfile in self._get_package_data_output_mapping():    
        File "env\lib\site-packages\setuptools\command\build_py.py", line 151, in _get_package_data_output_mapping
          for package, src_dir, build_dir, filenames in self.data_files:     
        File "env\lib\site-packages\setuptools\command\build_py.py", line 72, in __getattr__
          self.data_files = self._get_data_files()
        File "env\lib\site-packages\setuptools\command\build_py.py", line 84, in _get_data_files
          self.analyze_manifest()
        File "env\lib\site-packages\setuptools\command\build_py.py", line 181, in analyze_manifest
          self.run_command('egg_info')
        File "env\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "env\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "env\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "env\lib\site-packages\setuptools\command\egg_info.py", line 308, in run
          self.find_sources()
        File "env\lib\site-packages\setuptools\command\egg_info.py", line 316, in find_sources
          mm.run()
        File "env\lib\site-packages\setuptools\command\egg_info.py", line 560, in run
          self.add_defaults()
        File "env\lib\site-packages\setuptools\command\egg_info.py", line 604, in add_defaults
          self.read_manifest()
        File "env\lib\site-packages\setuptools\command\sdist.py", line 209, in read_manifest
          self.filelist.append(line)
        File "env\lib\site-packages\setuptools\command\egg_info.py", line 497, in append
          path = convert_path(item)
        File "env\lib\site-packages\setuptools\_distutils\util.py", line 137, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)        
      ValueError: path '/Users/rusty1s/github/pytorch_cluster/csrc/fps.cpp' cannot be absolute
      Error in atexit._run_exitfuncs:
      Traceback (most recent call last):
        File "env\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
          return stream.closed
      ValueError: underlying buffer has been detached
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> torch_cluster

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by rusty1s** [comment]
Can you try to upgrade to at least Python 3.8? We had some problems building Windows wheels for Python 3.7, and just upgrading Python should resolve all of this. Then
```
pip install torch-cluster -f https://data.pyg.org/whl/torch-1.12.1+cpu.html
```
should work as expected.
