### ISSUE TITLE
Expected object of scalar type Long but got scalar type Int for sequence elment 1 in sequence argument at position #1 'tensors'

### ISSUE THREAD

**Issue by TheNomet** [rusty1s/pytorch_cluster#19]
Hello, I was trying to run one of your examples in the documentation and found this.
```
import torch
from torch_cluster import knn_graph

x = torch.tensor([[-1, -1], [-1, 1], [1, -1], [1, 1]])
edge_index = knn_graph(x, k=2, loop=False)
```
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-58-47d38d59d882> in <module>
      3 
      4 x = torch.tensor([[-1, -1], [-1, 1], [1, -1], [1, 1]])
----> 5 edge_index = knn_graph(x, k=2, loop=False)

~\Anaconda3\lib\site-packages\torch_cluster\knn.py in knn_graph(x, k, batch, loop)
    105     """
    106 
--> 107     edge_index = knn(x, x, k if loop else k + 1, batch, batch)
    108     if not loop:
    109         row, col = edge_index

~\Anaconda3\lib\site-packages\torch_cluster\knn.py in knn(x, y, k, batch_x, batch_y)
     75     row, col = row.view(-1)[mask], col.view(-1)[mask]
     76 
---> 77     return torch.stack([row, col], dim=0)
     78 
     79 

RuntimeError: Expected object of scalar type Long but got scalar type Int for sequence elment 1 in sequence argument at position #1 'tensors'
```

**Comment by rusty1s** [comment]
`x` must be a floating type tensor, so you should eithee use `torch.Tensor` or `torch.tensor(..., dtype=torch.float)`.

**Comment by TheNomet** [comment]
```
import torch
from torch_cluster import knn_graph
x = torch.Tensor([[-1, -1], [-1, 1], [1, -1], [1, 1]])
edge_index = knn_graph(x, k=2, loop=False)
Traceback (most recent call last):
  File "C:\Users\fiore\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-9bf18e4256be>", line 5, in <module>
    edge_index = knn_graph(x, k=2, loop=False)
  File "C:\Users\fiore\Anaconda3\lib\site-packages\torch_cluster\knn.py", line 107, in knn_graph
    edge_index = knn(x, x, k if loop else k + 1, batch, batch)
  File "C:\Users\fiore\Anaconda3\lib\site-packages\torch_cluster\knn.py", line 77, in knn
    return torch.stack([row, col], dim=0)
RuntimeError: Expected object of scalar type Long but got scalar type Int for sequence elment 1 in sequence argument at position #1 'tensors'
```


```
import torch
from torch_cluster import knn_graph
x = torch.tensor([[-1, -1], [-1, 1], [1, -1], [1, 1]]).float()
x

Out[6]: 
tensor([[-1., -1.],
        [-1.,  1.],
        [ 1., -1.],
        [ 1.,  1.]])

edge_index = knn_graph(x, k=2, loop=False)

Traceback (most recent call last):
  File "C:\Users\fiore\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-08b386477039>", line 1, in <module>
    edge_index = knn_graph(x, k=2, loop=False)
  File "C:\Users\fiore\Anaconda3\lib\site-packages\torch_cluster\knn.py", line 107, in knn_graph
    edge_index = knn(x, x, k if loop else k + 1, batch, batch)
  File "C:\Users\fiore\Anaconda3\lib\site-packages\torch_cluster\knn.py", line 77, in knn
    return torch.stack([row, col], dim=0)
RuntimeError: Expected object of scalar type Long but got scalar type Int for sequence elment 1 in sequence argument at position #1 'tensors'
```

**Comment by rusty1s** [comment]
You are using Windows? This seems kinda related to https://github.com/rusty1s/pytorch_sparse/issues/13 where Windows/NumPy converts types differently than Linux/NumPy. I pushed a potential fix to master. It would be great if you could validate it.
