### ISSUE TITLE
No such operator torch_cluster::fps_ptr_list

### ISSUE THREAD

**Issue by Li-Yingda** [rusty1s/pytorch_cluster#193]
Hi, thanks for your help.
I'm trying to use torch_cluster,  I receive the following error:

```
      >>> import torch_cluster
      Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        File "/Users/eleme/anaconda3/envs/python3.8/lib/python3.8/site-packages/torch_cluster/__init__.py", line 39, in <module>
          from .fps import fps  # noqa
        File "/Users/eleme/anaconda3/envs/python3.8/lib/python3.8/site-packages/torch_cluster/fps.py", line 6, in <module>
          import torch_cluster.typing
        File "/Users/eleme/anaconda3/envs/python3.8/lib/python3.8/site-packages/torch_cluster/typing.py", line 3, in <module>
          WITH_PTR_LIST = hasattr(torch.ops.torch_cluster, 'fps_ptr_list')
        File "/Users/eleme/anaconda3/envs/python3.8/lib/python3.8/site-packages/torch/_ops.py", line 63, in __getattr__
          op = torch._C._jit_get_operation(qualified_op_name)
      RuntimeError: No such operator torch_cluster::fps_ptr_list
```

The libs version are:
```
        torch                         1.10.1
        torch-cluster                 1.6.2
        torch-geometric               2.3.1
        torch-scatter                 1.0.4
        torch-sparse                  0.2.2
        torch-spline-conv             1.0.4
        torchaudio                    0.10.1
        torchvision                   0.11.2
        tornado                       6.2
```

**Comment by rusty1s** [comment]
Thanks for letting me know. I am not sure if `torch-cluster==1.6.2` supports PyTorch 1.10, but it definitely supports 1.11. Can you downgrade `torch-cluster` to `1.6.1`? In the meantime, let me work on supporting older versions of PyTorch as well.

**Comment by rusty1s** [comment]
Fixed on master, will craft a new release soon.
