### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_cluster.graclus_cuda'

### ISSUE THREAD

**Issue by Shmyg** [rusty1s/pytorch_cluster#46]
Hi,

I have installed CUDA manually (as it was suggested in other issues), and it seems to be working fine:

```
shmyg@test-pc:~$ /usr/local/cuda-10.2/samples/bin/x86_64/linux/release/deviceQuery
/usr/local/cuda-10.2/samples/bin/x86_64/linux/release/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)
Device 0: "GeForce GTX 1050"
  CUDA Driver Version / Runtime Version          10.2 / 10.2
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 1997 MBytes (2094202880 bytes)
  ( 5) Multiprocessors, (128) CUDA Cores/MP:     640 CUDA Cores
  GPU Max Clock rate:                            1455 MHz (1.46 GHz)
  Memory Clock rate:                             3504 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 1048576 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.2, CUDA Runtime Version = 10.2, NumDevs = 1
Result = PASS
```

I've also checked all the environment variables:
```
shmyg@test-pc:~$ echo $PATH

/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin

shmyg@test-pc:~$ echo $CPATH

/usr/local/cuda/bin/include
```

But when I'm trying to use torch_cluster, it fails:

```
>>>import torch
>>>from torch_cluster import graclus_cluster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shmyg/.local/lib/python3.6/site-packages/torch_cluster/__init__.py", line 1, in <module>
    from .graclus import graclus_cluster
  File "/home/shmyg/.local/lib/python3.6/site-packages/torch_cluster/graclus.py", line 5, in <module>
    import torch_cluster.graclus_cuda
ModuleNotFoundError: No module named 'torch_cluster.graclus_cuda'`
```

What am I doing wrong?

**Comment by idoh** [comment]
I'm having the same problem.

**Comment by guangzufang** [comment]
Who has the solution to this problem?

**Comment by joongkyunKim** [comment]
I'm having the same problem.
